"""
Product Profitability Overview page for Nassau Candy Distributor dashboard.
Displays margin leaderboard, profit contribution chart, and sales-vs-margin quadrant scatter.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from src.profitability import analyze_product_profitability


def render_page_product(df: pd.DataFrame, search_query: str, margin_threshold: float):
    st.markdown("## 🍬 Product Profitability Overview")
    st.markdown("Analyze individual SKU economics, margin leaderboards, and profit contribution shares.")
    
    if df.empty:
        st.warning("No data available for the selected filters.")
        return
        
    # Recalculate product-level profitability metrics based on filtered order data
    prod_df = analyze_product_profitability(df, margin_threshold)
    
    # 1. Executive Top-Level KPIs
    total_sales = df["Sales"].sum()
    total_profit = df["Gross Profit"].sum()
    overall_margin = (total_profit / total_sales * 100.0) if total_sales > 0 else 0.0
    total_units = df["Units"].sum()
    
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.metric("Total Revenue", f"${total_sales:,.2f}")
    with c2:
        st.metric("Total Gross Profit", f"${total_profit:,.2f}")
    with c3:
        st.metric("Overall Gross Margin %", f"{overall_margin:.2f}%")
    with c4:
        st.metric("Total Units Sold", f"{total_units:,}")
        
    st.markdown("---")
    
    # 2. Charts Row (Scatter + Pie Chart)
    col_scatter, col_pie = st.columns([3, 2])
    
    with col_scatter:
        st.markdown("### 🧭 Sales vs Gross Margin Quadrant Scatter")
        st.markdown("Products mapped by Sales (X-axis) vs Gross Margin % (Y-axis), sized by Gross Profit.")
        
        # Calculate medians for boundaries
        median_sales = prod_df["Sales"].median() if not prod_df.empty else 0.0
        median_margin = prod_df["Gross Margin %"].median() if not prod_df.empty else 0.0
        
        fig_scatter = px.scatter(
            prod_df,
            x="Sales",
            y="Gross Margin %",
            size="Gross_Profit",
            color="Matrix Category",
            hover_name="Product Name",
            hover_data=["Product ID", "Division", "Gross_Profit", "Units", "Below Threshold Flag"],
            text="Product Name",
            color_discrete_sequence=px.colors.qualitative.Bold
        )
        # Add quadrant benchmark lines
        fig_scatter.add_vline(x=median_sales, line_dash="dash", line_color="#94a3b8", annotation_text=f"Median Sales (${median_sales:,.0f})")
        fig_scatter.add_hline(y=median_margin, line_dash="dash", line_color="#94a3b8", annotation_text=f"Median Margin ({median_margin:.1f}%)")
        
        # Highlight configurable threshold
        fig_scatter.add_hline(y=margin_threshold, line_color="#ef4444", line_dash="solid", annotation_text=f"Threshold ({margin_threshold:.1f}%)")
        
        fig_scatter.update_traces(textposition="top center")
        fig_scatter.update_layout(
            template="plotly_dark",
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            height=400,
            xaxis=dict(title="Total Sales ($)", gridcolor="rgba(255,255,255,0.08)"),
            yaxis=dict(title="Gross Margin %", gridcolor="rgba(255,255,255,0.08)")
        )
        st.plotly_chart(fig_scatter, use_container_width=True)
        
    with col_pie:
        st.markdown("### 📊 Product Profit Contribution %")
        st.markdown("Relative share of total gross profit generated by each product.")
        
        # Limit to top 6 products and group the rest into 'Other Products' to keep chart clean
        if len(prod_df) > 6:
            top_prods = prod_df.head(5).copy()
            other_profit = prod_df.iloc[5:]["Gross_Profit"].sum()
            other_row = pd.DataFrame([{
                "Product Name": "Other Products",
                "Gross_Profit": other_profit,
                "Profit Contribution %": (other_profit / total_profit * 100.0) if total_profit > 0 else 0.0
            }])
            pie_df = pd.concat([top_prods, other_row], ignore_index=True)
        else:
            pie_df = prod_df.copy()
            
        fig_pie = px.pie(
            pie_df,
            values="Gross_Profit",
            names="Product Name",
            hole=0.4,
            color_discrete_sequence=px.colors.sequential.Plotly3
        )
        fig_pie.update_traces(textinfo="percent+label")
        fig_pie.update_layout(
            template="plotly_dark",
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            height=400,
            showlegend=False,
            margin=dict(l=10, r=10, t=10, b=10)
        )
        st.plotly_chart(fig_pie, use_container_width=True)

        
    st.markdown("---")
    
    # 3. Product Leaderboard Table
    st.markdown("### 🏆 Product Margin Performance Leaderboard")
    st.markdown("Sorted leaderboard of Nassau Candy product catalog, ranked by Gross Profit descending (Step 2).")
    
    # Apply threshold flagging visually in the dataframe
    def style_threshold(row):
        is_below = row["Gross Margin %"] < margin_threshold
        color = "background-color: rgba(239, 68, 68, 0.25);" if is_below else ""
        return [color] * len(row)
        
    display_cols = [
        "Product ID", "Product Name", "Division", "Sales", "Cost", "Gross_Profit",
        "Gross Margin %", "Units", "Profit per Unit", "Revenue Contribution %",
        "Profit Contribution %", "Segment", "Below Threshold Flag"
    ]
    
    leaderboard_formatted = prod_df[display_cols].copy()
    
    # Format and present sorted leaderboard
    st.dataframe(
        leaderboard_formatted.style.apply(style_threshold, axis=1).format({
            "Sales": "${:,.2f}",
            "Cost": "${:,.2f}",
            "Gross_Profit": "${:,.2f}",
            "Gross Margin %": "{:.2f}%",
            "Units": "{:,}",
            "Profit per Unit": "${:.2f}",
            "Revenue Contribution %": "{:.2f}%",
            "Profit Contribution %": "{:.2f}%"
        }),
        use_container_width=True,
        height=400
    )

